apiVersion: v1
kind: Pod
metadata:
  name: kafka-client
  namespace: kafka
spec:
  containers:
  - name: kafka-client
    image: jorgegonzalezchakray/cp-kafka:5.2.2
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
