
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  http:
    - name: route-to-argocd
      match:
        hosts:
          - www.jorge-gonzalez.info
        paths:
          - /argo
      backends:
        - serviceName: argocd-server
          servicePort: 80
