# Use root/example as user/password credentials
version: '3'

services:
  db:
    container_name: "db_mysql"
    image: mysql:8.0.33
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - './data/var/lib/mysql:/var/lib/mysql'
    restart: always
    ports:
      - "3306:3306/tcp"

    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - mysql_apim

networks:
  mysql_apim:
    driver: bridge