apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
#  - 192.168.100.0/24
  - 192.168.100.150-192.168.100.160
#  - fc00:f853:0ccd:e799::/124
